name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Verify formatting
        run: yarn prettier --check .
      - name: Run lint
        run: yarn lint
      - name: Run test
        run: yarn test
      - name: Run build
        run: yarn build
